name: stock_watchlist
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  cupertino_icons: ^1.0.8  
  # A powerful HTTP client for Dart, used for making network requests like API calls, including support for interceptors, global configuration, and more.
  dio: ^5.7.0               
  # Simplifies value comparison in Dart objects, especially useful in Bloc pattern to easily compare states and events without manually overriding equality checks.
  equatable: ^2.0.5        
  flutter:
    sdk: flutter          
  # A state management package based on the Bloc pattern, helping to manage app state effectively, separating business logic from UI components.
  flutter_bloc: ^8.1.6      
  # A lightweight, fast NoSQL local database for Flutter, used for storing data locally (like watchlists or user preferences) without the need for internet connectivity.
  hive: ^2.2.3          
  # Used to access commonly used directories in the file system (e.g., temp, app documents directory), often necessary when working with local storage like Hive.
  path_provider: ^2.1.4   
dev_dependencies:
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
